# Remove dummy values later

values = {
    "{{WEEK}}": "",
    "{{D2C W SO}}": "",
    "{{D2C W YOY}}": "",
    "{{SKC W SO}}": "",
    "{{SKC W YOY}}": "",
    "{{SKC W YOY ABS}}": "",
    "{{SKC W FC}}": "",
    "{{SKC YTD SO}}": "",
    "{{SKC YTD YOY}}": "",
    "{{SKC YTD YOY ABS}}": "",
    "{{SKC YTD FC}}": "",
    "{{SKC Traffic YOY}}": "",
    "{{SKC CVR YOY}}": "",
    "{{SKC AOV YOY}}": "",
    "{{SKC Comments}}": "", 
    "{{SKC whats on}}": "", 
    "{{SKC whats to come}}": "",
    "{{LRP W SO}}": "",
    "{{LRP W YOY}}": "",
    "{{LRP W YOY ABS}}": "",
    "{{LRP W FC}}": "",
    "{{LRP YTD SO}}": "",
    "{{LRP YTD YOY}}": "",
    "{{LRP YTD YOY ABS}}": "",
    "{{LRP YTD FC}}": "",
    "{{LRP Traffic YOY}}": "",
    "{{LRP CVR YOY}}": "",
    "{{LRP AOV YOY}}": "",
    "{{LRP Comments}}": "",
    "{{LRP whats on}}": "", 
    "{{LRP whats to come}}": "",
}