# Remove dummy values later

values = {
    "{{WEEK}}": "",
    "{{D2C W SO}}": "",
    "{{D2C W YOY}}": "",
    "{{SKC W SO}}": "",
    "{{SKC W YOY}}": "",
    "{{SKC W YOY ABS}}": "",
    "{{SKC W FC}}": "",
    "{{SKC YTD SO}}": "",
    "{{SKC YTD YOY}}": "",
    "{{SKC YTD YOY ABS}}": "",
    "{{SKC YTD FC}}": "",
    "{{SKC Traffic YOY}}": "",
    "{{SKC CVR YOY}}": "",
    "{{SKC AOV YOY}}": "",
    "{{SKC Comments}}": "", 
    "{{SKC whats on}}": "", 
    "{{SKC whats to come}}": "",
    "{{LRP W SO}}": "",
    "{{LRP W YOY}}": "",
    "{{LRP W YOY ABS}}": "",
    "{{LRP W FC}}": "",
    "{{LRP YTD SO}}": "",
    "{{LRP YTD YOY}}": "",
    "{{LRP YTD YOY ABS}}": "",
    "{{LRP YTD FC}}": "",
    "{{LRP Traffic YOY}}": "",
    "{{LRP CVR YOY}}": "",
    "{{LRP AOV YOY}}": "",
    "{{LRP Comments}}": "",
    "{{LRP whats on}}": "", 
    "{{LRP whats to come}}": "",
}

kpi_map = [
    ('{{SKC W SO}}',        skc_df,   8,   col),   
    ('{{SKC W YOY}}',       skc_df,  10,  col),   
    ('{{SKC W YOY ABS}}',   skc_df,   9,  col),   
    ('{{SKC W FC}}',        skc_df,  99,  col),   
    ('{{SKC YTD SO}}',      skc_df,  99,  col),   
    ('{{SKC YTD YOY}}',     skc_df,  99,  col),   
    ('{{SKC YTD YOY ABS}}', skc_df,  99,  col), 
    ('{{SKC YTD FC}}',      skc_df,  99,  col),   
    ('{{SKC Traffic YOY}}', skc_df,  11,  col), 
    ('{{SKC CVR YOY}}',     skc_df,  16,  col),  
    ('{{SKC AOV YOY}}',     skc_df,  17,  col), 

    ('{{LRP W SO}}',        lrp_df,  8,   col),  
    ('{{LRP W YOY}}',       lrp_df,  99,  col),   
    ('{{LRP W YOY ABS}}',   lrp_df,  99,  col),   
    ('{{LRP W FC}}',        lrp_df,  99,  col),   
    ('{{LRP YTD SO}}',      lrp_df,  99,  col),   
    ('{{LRP YTD YOY}}',     lrp_df,  99,  col),   
    ('{{LRP YTD YOY ABS}}', lrp_df,  99,  col),   
    ('{{LRP YTD FC}}',      lrp_df,  99,  col),   
    ('{{LRP Traffic YOY}}', lrp_df,  11,  col),   
    ('{{LRP CVR YOY}}',     lrp_df,  16,  col),   
    ('{{LRP AOV YOY}}',     lrp_df,  17,  col),
]